kind: pipeline
type: docker
name: default

steps:
  - name: crawl
    image: hayd/deno:alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TZ: "Asia/Seoul"
    commands:
      - apk add --no-cache git tzdata
      - git remote set-url origin https://$${GITHUB_TOKEN}@github.com/${DRONE_REPO}.git
      - git fetch --all
      - git checkout -b gh-pages origin/gh-pages
      - git merge master --ff
      - deno run --allow-write --allow-net --allow-read ./.scripts/crawler.ts
      - git add .
      - git diff --quiet && git diff --staged --quiet || (git commit --author="Crawl Bot <crawlbot@alien.moe>" -m "Update json files at `date +'%Y-%m-%d'`"; git push -f origin gh-pages)

trigger:
  branch:
    - master
  event:
    - cron
