kind: pipeline
type: docker
name: default

steps:
  - name: crawl
    image: hayd/deno:alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk add --no-cache git
      - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${DRONE_REPO}.git
      - git pull origin gh-pages
      - git checkout origin/gh-pages
      - git rebase master
      - deno run --allow-write --allow-net ./.scripts/crawler.ts
      - git add .
      - git diff --quiet && git diff --staged --quiet || (git commit --author="Crawl Bot <crawlbot@alien.moe>" -m "Update json files"; git push origin origin/gh-pages)
    when:
      branch:
        - master
      event:
        - cron
